Dev
romainmenke/pusher pull request #27
Opened 2017-01-10 20:41 UTC by romainmenke

2017-01-13 15:52 UTC, fd commented on link/README.md
> +}
Try this:

```go
func Handler(handler http.Handler) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {

		if !link.CanPush(w, r) {
			handler(w, r)
			return
		}
  		  
		var p = pusher{writer: w}
		handler.ServeHTTP(&p, r)
  		  
	}
}
```

2017-01-13 15:54 UTC, fd requested changes

2017-01-13 15:54 UTC, fd commented on link/example/main.go
> +}
not a complete responsewriter

2017-01-13 15:54 UTC, fd commented on link/link.go
> +func CanPush(w http.ResponseWriter, r *http.Request) bool {
why not make tyis private and a part of `Push`

2017-01-13 15:54 UTC, fd commented on link/link.go
> +type pusher struct {
Not a complete response writer

2017-01-14 15:51 UTC, romainmenke commented on link/example/main.go
> +}
https://github.com/romainmenke/pusher/blob/dev/link/response_writer.go

2017-01-14 15:51 UTC, romainmenke commented on link/link.go
> +type pusher struct {
https://github.com/romainmenke/pusher/blob/dev/link/response_writer.go

2017-01-14 15:52 UTC, romainmenke commented on link/link.go
> +func CanPush(w http.ResponseWriter, r *http.Request) bool {
Because it has to be evaluated with the request, not the response.

2017-01-14 15:52 UTC, romainmenke commented on link/README.md
> +}
https://github.com/romainmenke/pusher/blob/dev/link/link.go#L9-L21

2017-01-23 20:43 UTC, merged